### ISSUE TITLE
Refactor newMetachain

### ISSUE THREAD

**Issue by deepesh-kn** [OpenST/compute#100]
- Move constants EPOCH_LENGTH from Axiom to Consensus contract. Add a constant MAX_STATE_ROOTS in Consensus contract 

Refactor:Axiom::newMetachain

- Remove all params from axiom:newMetachain()
- Remove all the logic related to maxStateRoot and rootRlpBlockHeader.
- Call consensus.newMetaChain.
- Get the metachainId as the return value of consensus.newMetaChain
- Emit an event MetachainCreated

Refactor: Consensus::newMetachain

- Add a new mapping consensusGateways (metachainId bytes32 -> consensusGateway address)
- Call Axiom::deployMetachainProxies
- Generate metachainId.
- ~~Update the CoreLifetime status to Creation~~ (done in newCore already)
- Update assignments mapping.
- Update consensusGateways mapping
- Return metachainId

**Comment by 0xsarvesh** [comment]
`consensus.newMetaChain`:  Core setup function requires`metachainId`, both core and anchor is deployed with `axiom.deploymetachainProxies`. Hence meta chain ID is not available. 

The proposal is to split anchor deployment from `deployMetachainProxies`.

**Comment by deepesh-kn** [comment]
You are correct 👍 

- Deploy Anchor,
- Generate `metachainId` and then call `deployMetachainProxies`
- `deployMetachainProxies` will deploy `Core`, and `ConsensusGateway`.
