### ISSUE TITLE
Implement the KERNEL_INTENT_TYPEHASH constant and hashKernelIntent function in ConsensusGatewayBase contract 

### ISSUE THREAD

**Issue by jayeshbairagi** [OpenST/compute#119]
- Create a constant `bytes32` variable `KERNEL_INTENT_TYPEHASH` for storing kernel intent type hash. 
  - This will be used in `hashKernelIntent` function for the creation of `kernelIntentHash_`
```solidity
bytes32 public constant KERNEL_INTENT_TYPEHASH = keccak256(
    abi.encode(
        "KernelIntent(uint256 height,bytes32 kernelHash)"
    )
)
```
- Create the function `hashKernelIntent` 
  - Parameters:
    - `uint256 _height` and
    - `bytes32 _kernelHash`
  - Returns:
    - `bytes32 kernelIntentHash_`
  - This function will be called from `declareOpenKernel` function 
```solidity
function hashKernelIntent(
    uint256 _height,
    bytes32 _kernelHash
) 
    public 
    returns (bytes32 kernelIntentHash_) 
```
- The function `hashKernelIntent` will be used by `ConsensusGateway` and `ConsensusCogateway` contracts

**Comment by 0xsarvesh** [comment]
@jayeshbairagi  @deepesh-kn 

Should there be`nonce` of core/consensus in kernel intent hash?

**Comment by 0xsarvesh** [comment]
Discussion: 
nonce will be hashed with message hash in the message bus.
