### ISSUE TITLE
Implement ConsensusGateway contract

### ISSUE THREAD

**Issue by jayeshbairagi** [OpenST/compute#123]
- `ConsensusGateway` contract will be dependent on `ConsensusGatewayBase` contract
- This contract should follow the proxy pattern
```solidity
contract ConsensusGateway is MasterCopyNonUpgradable, MessageBus, ConsensusGatewayBase, ConsensusModule, ERC20GatewayBase
```
- The inheritance sequence of `MasterCopyNonUpgradable` and `MessageBus` such that,
    - `MasterCopyNonUpgradable` should be at inclusionIndex 0
    - `MessageBus` should be at inclusionIndex 1
- Variables to be defined for this contract:
  - Define the constants for storage index of message box outbox and message box inbox mappings:
    - `uint8 constant public OUTBOX_OFFSET = <Identify this>;`
    - `uint8 constant public INBOX_OFFSET = <Identify this>;`
- Define a function `setup` in `ConsensusGateway` contract
  - `setup` function can be called only once
  - This will be an `external` function
```solidity
function setup(
    bytes32 _metachainId,
    address _consensus,
    ERC20I _most,
    address _consensusCogateway,
    uint8 _outboxStorageIndex,
    uint256 _maxStorageRootItems,
) 
    external
```
- The `setup` function will call the `setupConsensusGatewayBase` function of `ConsensusGatewayBase` with the `_consensus` address as parameter
  - This will set up `_consensus` in `ConsensusModule` contract and `ERC20I _most`
```solidity
ConsensusGatewayBase.setupConsensusGatewayBase(_consensus, _most);
```
- The `setup` function will call the `setupMessageOutbox` function of `MessageOutbox` with `_metachainId`, `_consensusCogateway`, `address(this)` as parameters
```solidity
MessageOutbox.setupMessageOutbox(
    _metachainId,
    _consensusCogateway,
    address(this)
);
```
- The `setup` function will call the `setupMessageInbox` function of `MessageInbox` with  `_metachainId`, `_consensusCogateway`, `_outboxStorageIndex`, `_maxStorageRootItems`, `address(this)` as parameters
```solidity
MessageInbox.setupMessageInbox(
    _metachainId,
    _consensusCogateway,
    _outboxStorageIndex,
    _maxStorageRootItems,
    address(this)
);
```

**Comment by 0xsarvesh** [comment]
This issue is blocked by #120 , Hence moving back to the backlog.

**Comment by 0xsarvesh** [comment]
@jayeshbairagi Below is implemented. Please check if it's correct. This  will help speed up review process. 

Note: `ConsensusModule` is missing(in the ticket description) and ~~`ERC20GatewayBase` is not available at the time of implementation.~~
```
contract ConsensusGateway is MasterCopyNonUpgradable, MessageBus, ConsensusGatewayBase, ConsensusModule
```

**Comment by 0xsarvesh** [comment]
Also, below is the new signature of setup method. As consensus is going to create setup data from consensus gateway, stateRootProvider address is passed on setup. 

Please confirm if below looks good. 

```
    function setup(
        bytes32 _metachainId,
        address _consensus,
        ERC20I _most,
        address _consensusCogateway,
        StateRootI _stateRootProvider,
        uint256 _maxStorageRootItems,
        uint8 _outboxStorageIndex
    )
```

**Comment by jayeshbairagi** [comment]
- For the given `_metachainId` we can get the `_stateRootProvider`/`anchor` from `_consensus`. In this contract, we cant be sure that the call data for setup is generated in consensus contract. I will make a note of this and can be optimized later.

- Yes, we can add `ConsensusModule`(I have updated the ticket description), and `ERC20GatewayBase` is also available so we can use that.
- `ConsensusModule.setupConsensus()` should be called here.

**Comment by pgev** [comment]
https://github.com/mosaicdao/mosaic-1/pull/149
