### ISSUE TITLE
Implement a function declareOpenKernel in ConsensusGateway contract

### ISSUE THREAD

**Issue by jayeshbairagi** [OpenST/compute#124]
- Create the function `declareOpenKernel`
  - This function will be used to declare open kernel
  - This will be an `external` function
  - Parameters:
    - `CoreI _core`, `Core` contract address
    - `uint256 _feeGasPrice`
    - `uint256 _feeGasLimit`
  - Modifiers:
    - `onlyConsensus`
  - Returns:
    - `bytes32 messageHash_`
```solidity
function declareOpenKernel(
    CoreI _core, 
    uint256 _feeGasPrice, 
    uint256 _feeGasLimit
)
    onlyConsensus
    external
    returns (bytes32 messageHash_)
```
- This function asserts that the `_core` address is not zero
- Get the `openKernelHeight` and `openKernelHash` from `Core` contract
  - Here we get the required values i.e the `height` and `kernelHash` from the `Core` contract in one call instead of two calls
 ```solidity
(height, kernelHash) = _core.getOpenKernel();
```
- The height can be equal to `currentMetablockHeight` or `currentMetablockHeight + 1`. 
  - We should allow equal height, in case of chain halting when the new Core is created, then the new kernel can be opened at the same height. 
  - As this function can be called only by `consensus`, we can trust that same height will not be passed in normal conditions. (Used for recovering from halted Core, then new Core can resume at same `KernelHeight`)
- Set the `currentMetablockHeight`
```solidity
currentMetablockHeight = height;
```
- Create the `kernelIntentHash`. It is EIP712(height, kernelHash)
  - This will call the `hashKernelIntent` function of the `ConsensusGatewayBase` contract 
```solidity
hashKernelIntent(height, kernelHash);
```
- Increment nonce for the caller(from nonces mapping)
  - First Nonce will be `0`
  - Use `safeMath.sol` for adding the `nonces`
```solidity
uint256 nonce = nonces[msg.sender];
nonces[msg.sender].add(1);
```
- Call the `MessageOutbox.declareMessage`
  - This will update the outbox value to `true` for the given message hash in `MessageOutbox`
```solidity
MessageOutbox.declareMessage(kernelIntentHash, nonce, _feeGasPrice, _feeGasLimit, msg.sender);
```

**Comment by abhayks1** [comment]
```
(height, kernelHash) = _core.getOpenKernel();
```
Above interface is outdated. Below is updated interface:
```
function getOpenKernel() external returns (bytes32, uint256);
```

**Comment by pgev** [comment]
https://github.com/mosaicdao/mosaic-1/pull/158
