### ISSUE TITLE
Implement a function to deposit MOST on origin chain

### ISSUE THREAD

**Issue by jayeshbairagi** [OpenST/compute#125]
- Create the `deposit` function 
  - This will `deposit` the `MOST` on the origin chain and `mint` the `utMOST` on the auxiliary chain
  - This will be an `external` function
```solidity
function deposit(
    uint256 _amount,
    address _beneficiary,
    uint256 _feeGasPrice,
    uint256 _feeGasLimit,
)
    external
```
- Anyone can call this function to deposit MOST
- Input parameters should be validated
  - Check if the reward is possible with given input parameters
    - `amount` 
    - `_feeGasPrice`
    - `_feeGasLimit` 
If the reward is not possible then revert
- Generate the `depositIntentHash`
  - Call `hashDepositIntent` function of the `ERC20GatewayBase` to get the `depositIntentHash`
```solidity
hashDepositIntent(_amount, _beneficiary)
```
- Increment nonce for the caller(from nonces mapping)
  - First Nonce will be `0`
  - Use `safeMath.sol` for adding the `nonces`
```solidity
uint256 nonce = nonces[msg.sender];
nonces[msg.sender].add(1);
```
- Call the `MessageOutbox.declareMessage` function 
  - This will update the outbox value to `true` for the given message hash in `MessageOutbox`
```solidity
MessageOutbox.declareMessage(depositIntentHash, nonce, _feeGasPrice, _feeGasLimit, msg.sender);
```
- Transfer `_amount` number of the MOST(s) from the `address(msg.sender)` to ConsensusGateway's `address(this)`

**Comment by pgev** [comment]
https://github.com/mosaicdao/mosaic-1/pull/154
