### ISSUE TITLE
Follow mock pattern from Openzeppelin 

### ISSUE THREAD

**Issue by jayeshbairagi** [OpenST/compute#153]
Understand and implement the mock pattern from Openzeppelin in our contracts
- Reference: https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/mocks/ERC20Mock.sol

**Comment by 0xsarvesh** [comment]
It seems Openzeppelin doesn't publish mock token in it's dependency. 

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/67a71519d32d413aae17d89ae1d9ff1963226704/package.json#L8

**Comment by jayeshbairagi** [comment]
We are not going to use ERC20Mock.sol contract by importing it directly. The aim is to replicate the implementation around mock.

Yes, you are right that this is not published as a dependency.

**Comment by 0xsarvesh** [comment]
ERC20 from openzeppelin doesn't allow transfer to `0` address. 
https://github.com/OpenZeppelin/openzeppelin-contracts/blob/f9650b4cb897fe71c049902dab9975bd702b5325/contracts/token/ERC20/ERC20.sol#L156

In the reputation contract, there is logic to burn token by transferring to `0` address.

https://github.com/mosaicdao/mosaic-1/blob/4ca731f9ab07d6787dc63299789380d1c659e24a/contracts/reputation/Reputation.sol#L488

**Comment by 0xsarvesh** [comment]
For now, the burner address in reputation is set to address(1).
