### ISSUE TITLE
Implement MessageBox::hashChannelIdentifier and MessageBox::hashMessage function and dependent constants

### ISSUE THREAD

**Issue by jayeshbairagi** [OpenST/compute#156]
- Create the constant `MMB_CHANNEL_TYPEHASH`
```solidity
bytes32 public constant MMB_CHANNEL_TYPEHASH = keccak256(
    "MosaicMessageBusChannel(address outbox, address inbox)"
);
```
- Create the constant `MMB_DOMAIN_SEPARATOR_NAME`
```solidity
string public constant MMB_DOMAIN_SEPARATOR_NAME = "Mosaic-Bus";
```
- Create the constant `MMB_DOMAIN_SEPARATOR_VERSION`
```solidity
string public constant MMB_DOMAIN_SEPARATOR_VERSION = "0";
```
- Create the constant `MMB_DOMAIN_SEPARATOR_TYPEHASH`
```solidity
bytes32 public constant MMB_DOMAIN_SEPARATOR_TYPEHASH = keccak256(
    "MosaicMessageBus(string name,string version,bytes32 metachainId,bytes32 channelSeparator)"
);
```
- Implement the function `hashChannelIdentifier` to create the hash of the channel identifier
  - Parameters:
    - `bytes32 _metachainId`
    - `address _outbox`
    - `address _inbox`
  - Returns:
    - `bytes32 channelIdentifier_`
  - Implementation
  ```solidity
  function hashChannelIdentifier(
      bytes32 _metachainId,
      address _outbox
      address _inbox,    
  ) 
      public 
      pure
      returns (bytes32 channelIdentifier_) 
  {
      bytes32 channelHash = keccak256(
          abi.encode(
              MMB_CHANNEL_TYPEHASH,
              _outbox,
              _inbox
          )
      );
    
      channelIdentifier_ = keccak256(
         abi.encode(
              MMB_DOMAIN_SEPARATOR_TYPEHASH,
              MMB_DOMAIN_SEPARATOR_NAME,
              MMB_DOMAIN_SEPARATOR_VERSION,
              _metachainId,
              channelHash
          )
      );
  }    
  ```
- **Note:**
  - For outbound messages, the channel identifier will be calculated as 
  ```solidity
  bytes32 outboundChannelIdentifier = hashChannelIdentifier(
      metachainId,
      outboxAddress,
      inboxAddress
  );
  ```
  - For inbound messages, the channel identifier will be calculated as 
  ```solidity
  bytes32 inboundChannelIdentifier = hashChannelIdentifier(
      metachainId,
      inboxAddress,
      outboxAddress
  );
  ```

- Update the `MESSAGE_TYPEHASH` as:
  ```solidity
  bytes32 public constant MESSAGE_TYPEHASH = keccak256(
      "Message(bytes32 intentHash,uint256 nonce,uint256 feeGasPrice,uint256 feeGasLimit,address sender)"
  );
  ```
- The function `messageHash` will be updated to `hashMessage` as:
  - Parameters:
    - `bytes32 _intentHash`
    - `uint256 _nonce`
    - `uint256 _feeGasPrice`
    - `uint256 _feeGasLimit`
    - `address _sender`
    - `bytes32 _channelIdentifier`
  - Returns:
    - `bytes32 messageHash_`
  - The `_channelIdentifier` will be implemented using the `hashChannelIdentifier` function 
  - Implementation:
  ```solidity
  function hashMessage(
      bytes32 _intentHash,
      uint256 _nonce,
      uint256 _feeGasPrice,
      uint256 _feeGasLimit,
      address _sender,
      bytes32 _channelIdentifier
  )
      internal
      pure
      returns (bytes32 messageHash_)
  {

      bytes32 typedMessageHash = keccak256(
          abi.encode(
              MESSAGE_TYPEHASH,
              _intentHash,
              _nonce,
              _feeGasPrice,
              _feeGasLimit,
              _sender
          )
      );

      messageHash_ = keccak256(
          abi.encodePacked(
              byte(0x19),
              byte(0x4d), // 0x4d is for M (Mosaic)
              _channelIdentifier,
              typedMessageHash
          )
      );
  }
  ```

**Comment by abhayks1** [comment]
Started working on this ticket 🚗

**Comment by abhayks1** [comment]
```
Update the MESSAGE_TYPEHASH as:

bytes32 public constant MESSAGE_TYPEHASH = keccak256(
    "Message(bytes32 intentHash,uint256 nonce,uint256 feeGasPrice,uint256 feeGasLimit,address sender)"
);
```
@jayeshbairagi What's the change in MESSAGE_TYPEHASH 😕 ? It's already update as above in the contract.
https://github.com/mosaicdao/mosaic-1/blob/feature/consensus/contracts/message-bus/MessageBox.sol#L36

**Comment by jayeshbairagi** [comment]
@abhayks1, thank you for pointing that out. In this case, you don't have to update it. Please proceed further.

**Comment by abhayks1** [comment]
- Interface of setupMessageInbox needs to be updated since `verifyingAddress` is not needed now. Updated interface is below:
```
function setupMessageInbox(
        bytes32 _metachainId,
        address _messageOutbox,
        uint8 _outboxStorageIndex,
        StateRootI _stateRootProvider,
        uint256 _maxStorageRootItems
    )
    internal
```

- Interface of setupMessageOutbox needs to be updated since `verifyingAddress` is not needed. Updated interface is below:
```
function setupMessageOutbox(
        bytes32 _metachainId,
        address _messageInbox
    )
        internal
```

cc: @jayeshbairagi @deepesh-kn

**Comment by abhayks1** [comment]
Updating the **outboundChannelIdentifier** calculation updated logic:
```
outboundChannelIdentifier = MessageBox.hashChannelIdentifier(
            _metachainId,
            address(this),
            messageInbox
        );
```
For ConsensusGateway => outboundChannelIdentifier
- messageOutbox is consensusGateway(address(this) is ConsensusGateway address here after inheritance)
- messageInbox is ConsensusCoGateway address

Updating the **inboundChannelIdentifier** calculation updated logic:
```
inboundChannelIdentifier = MessageBox.hashChannelIdentifier(
            _metachainId,
            messageOutbox,
            address(this)
        );
```
For ConsensusGateway => inboundChannelIdentifier
- messageOutbox is consensusCoGateway address
- messageInbox is ConsensusGateway (address(this) is ConsensusGateway address after inheritance)

cc: @deepesh-kn @jayeshbairagi  @pgev

**Comment by pgev** [comment]
https://github.com/mosaicdao/mosaic-1/pull/160
