### ISSUE TITLE
Implementation of Coreputation contract inheritance and storage, enums

### ISSUE THREAD

**Issue by jayeshbairagi** [OpenST/compute#164]
1. `CoconsensusModule` will have a fixed constant `Coconsensus` address from the genesis.
2. Coconsensus.setup method is not needed since `Coconsensus` address is constant.
3. Define `ValidatorStatus` enum. ValidatorStatus enum values are `Undefined`, `Slashed`, `Staked`, `Deregistered`.
4. Define `ValidatorInfo` struct. Proposed state variables in the struct are below:
    - Validator status
    - Reputation value
5. Define the mapping of the validator address versus ValidatorInfo.
    ```solidity
    mapping(address => ValidatorInfo) public validators
    ```
6. The CoReputation contract should follow the proxy pattern for deployment.
7. `Coreputation` is `MasterCopyNonUpgradable`, `CoconsensusModule`

**Comment by abhayks1** [comment]
Added a **TODO** to remove setup method after coConsensus storage variable is made
constant in CoConsensusModule. Keeping setup method for testing purpose.
