### ISSUE TITLE
Implement ValidatorSet::forwardValidatorSetCount()

### ISSUE THREAD

**Issue by jayeshbairagi** [OpenST/compute#167]
1. Implement `ValidatorSet::forwardValidatorSetCount()` public view
    -  Keeps the count of all the validators in the forward validator set for a given metablock height
    - The counting will be done such that every time the validator is updated through the functions `insertValidator` and `removeValidator`, total count changes

Note: Need to consider all the cases when the validator set updates

**Comment by gulshanvasnani** [comment]
To get forward validator set count proposal is as follows :
1. Add a validatorCount mapping
 ```
mapping(uint256 /* kernelheight */ => uint256 /* validator count */) public validatorCount;
 ```
2. Add **kernelHeight** param in insert validator and remove validator functions.
3. Increase validator count for a kernel height in **insertValidator** method.
4. Decrease validator count for a kernel height in **removeValidator** method.

**Comment by benjaminbollen** [comment]
@gulshanvasnani we need to count the ForwardValidatorSet count specifically

**Comment by benjaminbollen** [comment]
In #242 I put forward an implementation for calculating the number of validators in the forward validator set. It has gotten some review comments from Pro, which I've incorporated.

Tomorrow I have to work on other tasks outside of the sprint, so putting this ticket in backlog for unit tests to be written (cc @jayeshbairagi).

Either write unit tests without looking at the implementation (reverse "tdd" :D), or feel free to first review and leave review comments.
