### ISSUE TITLE
Implement Coreputation::upsertValidator()

### ISSUE THREAD

**Issue by jayeshbairagi** [OpenST/compute#169]
1. Coconsensus contract should be able to add validator in Coreputation contract. Only Coconsensus should update validator information. 
2. Validator reputation value should be updated. 
3. Validator status should be marked to `Staked` if validator status is `Undefined` and has non zero reputation value.
4. Validator status should be marked to `Deregistered` when the current status is `Staked` and reputation value changes to zero value.
in Coreputation already). 
    - Proposal:
        ```solidity
        function upsertValidator(
            address _validator,
            uint256 _reputation
        )
            external
            onlyCoconsensus
        ```

**Comment by abhayks1** [comment]
@jayeshbairagi this ticket is not dependent on "Implement ValidatorSet::forwardValidatorSetCount()" ticket.
It had dependency on ticket "Implementation of Coreputation contract inheritance and storage, enums" which is merged.
