### ISSUE TITLE
Implement GenesisOriginObserver, OriginObserver contracts

### ISSUE THREAD

**Issue by jayeshbairagi** [OpenST/compute#177]
1. Implement `GenesisOriginObserver` contract
    - It will have `genesisBlockNumber` and `genesisStateRoot`;
2. Implement `OriginObserver` contract 
    - `OriginObserver is MasterCopyNonUpgradable, GenesisOriginObserver, CoconsensusModule, StateRootProvider`
3. Implement `OriginObserver::setup()`
    - Proposal
        ```solidity
        function setup(
            bytes32 _stateroot,
            uint256 _blockheight,
            address _consensus,
            uint256 maxStateRootLimitCount            
        )
            external
        ```
4. Implement `OriginObserver::anchorStateRoot()`
    - This will call the internal function`StateRootProvider::_anchorStateRoot`

**Comment by deepesh-kn** [comment]
Done with the implementation but tests are breaking due to changes made in coconsensus module contract, so parking this ticket for a while and picking up this https://github.com/mosaicdao/mosaic-1/issues/211. This ticket will fix my tests and will be needed by almost all contracts.

**Comment by deepesh-kn** [comment]
Please note that `OriginObserver::setup()` will not require any parameters.
The params needed will already be available in the genesis variables.

**Comment by benjaminbollen** [comment]
small semantic note; anchor state root now refers to "block numbers"
