### ISSUE TITLE
Implement Protocore::_registerVote()

### ISSUE THREAD

**Issue by jayeshbairagi** [OpenST/compute#182]
1. Implement `Protocore::registerVoteInternal()` 
    - This will be an internal function
    - This function registers a vote for a link specified by vote message hash
    - Checks if `_voteMessageHash` is 0.
    - Checks if the link mapping to the `_voteMessageHash` exists.
    - Checks if the metablock height of the link pointed by `_voteMessageHash` is equal to the open metablock height or open metablock height minus 1.
    - Only an active validator can call.
    - If the quorum is reached then for the link pointed by `_voteMessageHash` targetFinalisation is set to `justified`. If the link length is equal to the epoch length (finalisation link) then it marks targetFinalisation of the link pointed by `parentVoteMessageHash` as finalised.
    - Calls coconsensus if the source checkpoint of the link is finalised.
    - Emits event `Protocore::VoteRegistered`
    - Emits event `Protocore::LinkUpvoted`
    - Proposal
    ```solidity
    function _registerVote(
        bytes32 _voteMessageHash,
        bytes32 _r,
        bytes32 _s,
        uint8 _v
    )
        internal
    ```

**Comment by pgev** [comment]
The on-going implementation is caught at the following draft PR: https://github.com/mosaicdao/mosaic-1/pull/224

The draft implementation is there: not tested and properly reviewed, however all pieces are implemented.

**Comment by benjaminbollen** [comment]
Taking over as implementer (from reviewer)

**Comment by benjaminbollen** [comment]
checklist:
- [x] Checks if the link mapping to the _voteMessageHash exists.
- [x] Checks if the metablock height of the link pointed by _voteMessageHash is equal to the open metablock height or open metablock height minus 1.
- [x] ~Only an active validator can call.~ signature must be for an active validator
- [x] If the quorum is reached then for the link pointed by _voteMessageHash targetFinalisation is set to justified. If the link length is equal to the epoch length (finalisation link) then it marks targetFinalisation of the link pointed by parentVoteMessageHash as finalised.
- [x] Calls coconsensus if the source checkpoint of the link is finalised.
- [ ] Emits event Protocore::VoteRegistered
- [ ] Emits event Protocore::LinkUpvoted

new:
- [ ] write proper behavioural tests for `Protocore::registerVoteInternal`

**Comment by benjaminbollen** [comment]
in #235 I refactored the implementation, next
1. @pgev can you review, other reviewers welcome too
2. on this branch other unit tests are failing; I have not investigated cc @jayeshbairagi @deepesh-kn 
3. the events need to be emitted, and minimal unit tests; please put #182 back in backlog for that
4. and proper behavioural tests need to be written (new ticket) @jayeshbairagi
