### ISSUE TITLE
Implement Protocore::hashVoteMessage()

### ISSUE THREAD

**Issue by jayeshbairagi** [OpenST/compute#183]
1. Implement `Protocore::hashVoteMessage()`
    - This will be a private function
    - This function will take vote message parameters and returns the typed vote message hash
    - Proposal
    ```solidity
    function hashVoteMessage(
        bytes32 _sourceTransitionHash,
        bytes32 _sourceBlockHash,
        bytes32 _targetBlockHash,
        uint256 _sourceBlockNumber,
        uint256 _targetBlockNumber
    )
        private
        view
        returns (bytes32 voteMessageHash_)
    ```

**Comment by gulshanvasnani** [comment]
@jayeshbairagi , OriginProtocore and SelfProtocore contract will inherit Protocore contract. I think **hashVoteMessage** will be used in these contracts. So better to make the visibility of **hashVoteMessage** as internal.
Let me know what you think.

**Comment by benjaminbollen** [comment]
only `ProtocoreAbstract` needs to access this function (in `ProtocoreAbstract::_proposeLink`)
