### ISSUE TITLE
Implement GenesisOriginProtocore contract

### ISSUE THREAD

**Issue by jayeshbairagi** [OpenST/compute#184]
1. Implement the `GenesisOriginProtocore` contract
    - It has initial parameters for the initial link
    - We store the initial link at the genesis that defines the initial point where we start the metachain
    - All the parameters from the `Link` struct will be set here

**Comment by deepesh-kn** [comment]
I think that only the source block hash and source block number will be sufficient. The link object can be formed using that in setup functions. Let me know if I am missing something here.

**Comment by benjaminbollen** [comment]
it s the target checkpoint, so suggested to change the documentation, and also to make the variable name more explicit
