### ISSUE TITLE
Update Core contract

### ISSUE THREAD

**Issue by jayeshbairagi** [OpenST/compute#192]
1. Utilize `ValidatorSet` contract functionality by inheriting from it
2. Emit `Core::CoreStatusUpdated` event
3. Emit `Core::GenesisOriginObservationStored`

**Comment by benjaminbollen** [comment]
Note: Core contract has references `sourceBlockHeight` and related; please also update these to `BlockNumber`s, reserving "height" for metablocks

**Comment by benjaminbollen** [comment]
Following Gulshans work here, we realised that there is a miss(ing)-initialization in `Consensus` and `SelfProtocore`.  I will continue from Gulshan's branch (as he is now OOO), and include those last discussion notes.

**Comment by benjaminbollen** [comment]
under `Consensus::NewMetachain(...)`, we should
- initialize the metablock tip to `zero`
- store an initial committed metablock with `Height=0` and `round=Committed`
- create the assigned `Core` with `creationHeight=Height+1`

under `SelfProtocore`, we have a `genesisProposedMetablockHeight=0` (the same zero as committed metablock height at `newMetachain`).
We should:
- set the `openKernelHeight` of SelfProtocore under `setup` to `genesisProposedMetablockHeight` (equals zero); set `ValidatorSet(activeHeight = openKernelHeight+1)`

then all aligns; as a short recap; for a new metachain, MBlock0 is defined as committed and is the GenesisBlock; then the first Core assigned starts the first Metablock as MB1 (not zero as I previously thought). 

So also, MB0 has an empty validator set; then the Core is created and validators can join; they join the validator set at creationHeight=1;

this Kernel (H=1) is declared as a message on the ConsensusGateway; on the metachain the kernel opening is confirmed with H=1 (validators get upserted at H=1; coconsensus calls `SelfProtocore::openKernel(H=1, ...)` and the proposed links are proposed (either at H=0(no validators) or H=1(initial validators)
