### ISSUE TITLE
Rename contracts and variables

### ISSUE THREAD

**Issue by jayeshbairagi** [OpenST/compute#208]
Rename
- [ ] `newMetaChain` to `newMetachain`
- [ ] `CoConsensusModule` to `CoconsensusModule`
- [ ] `CoConsensusI` to `CoconsensusInterface`
- [ ] `setupCoConsensus` to `setupCoconsensus`
- [ ] `consensusCoGateway` to `consensusCogateway`

- [ ] Interfaces should have the `Interface` postfix in naming.
  `Example`
  > ConsensusInterface, GatewayInterface

**Comment by gulshanvasnani** [comment]
@jayeshbairagi, contracts which are used for testing purpose can also be renamed.
Like, `SpyAnchor` to `AnchorSpy`.

**Comment by jayeshbairagi** [comment]
@gulshanvasnani, this will be handled separately.

Thanks for pointing it out.
