### ISSUE TITLE
Require a validator to be in the validator set for open metablock height while registering its vote

### ISSUE THREAD

**Issue by pgev** [OpenST/compute#254]
In the current implementation, there is no check in `Protocore::registerVoteInternal` function that a validator that registers its vote is in the validator set for the open metablock height. Because of this if the validator set is empty a quorum will be reached by anyone calling this function.

**Comment by gulshanvasnani** [comment]
@pgev , is it fixed in PR https://github.com/mosaicdao/mosaic-1/pull/258 ?

**Comment by pgev** [comment]
@gulshanvasnani yes.
