### ISSUE TITLE
Update ERC20GatewayBase, ConsensusGateway and ConsensusCogateway.

### ISSUE THREAD

**Issue by deepesh-kn** [OpenST/compute#268]
- ERC20GatewayBase:
    - Update `DEPOSIT_INTENT_TYPEHASH` and `hashDepositIntent()` to include `address valueToken`.
    - Update `WITHDRAW_INTENT_TYPEHASH` and `hashWithdrawIntent()` to include `address valueToken,address utilityToken`.
- ConsensusGateway:
    - Update `deposit` function to pass most token in `hashDepositIntent()`.
    - Update `confirmWithdraw` function to pass most and utbase token address in `hashWithdrawIntent()`.
- ConsensusCogateway:
    - Update `withdraw` function to pass most and utbase token address in `hashWithdrawIntent()`.
    - Update `confirmDeposit` function to pass most address in `hashDepositIntent()`.

**Comment by abhayks1** [comment]
Moving this ticket to Backlog as it's dependent on ticket #225
