### ISSUE TITLE
Implement integration test for deposit flow

### ISSUE THREAD

**Issue by deepesh-kn** [OpenST/compute#277]

**Comment by 0xsarvesh** [comment]
Finished setup of integration test, available in https://github.com/sarvesh-ost/mosaic-1/tree/deposit_integration_tests.

@Vindeep07 will continue with tests.

**Comment by Vindeep07** [comment]
Finished Deployment, Setup and deposit method (including proof generation) of deposit flow, available in https://github.com/Vindeep07/mosaic-1/tree/deposit_integration_tests
