### ISSUE TITLE
Emit event MetablockProposed in Core.proposeMetablock

### ISSUE THREAD

**Issue by abhayks1** [OpenST/compute#65]
Validators will need to know proposal value for calling registerVote. 
  There are couple of approaches for validators to get proposal value after proposeMetablock method is called.

  **Approach 1:**

  Emit an event with bytes32 proposal value in proposeMetablock method. 

  emit MetablockProposed(bytes32 _proposal)
  Validators can listen to this event to get proposal value and call registerVote.

  **Approach 2:**

  Use graph node Call Handlers. Whenever proposeMetablock method is called, an enitity record 
 is created which validators can subscribe to.
  Note: Call handlers have few limitations.  It only works on parity node. They are slow to process.
  https://thegraph.com/docs/define-a-subgraph#call-handlers

Emitting event will be effective.

**Comment by benjaminbollen** [comment]
Validators should not sign based on `Core:proposeMetablock`; the signatures have already been created during the flow of ProtoCore;

argument for emitting event is for the tests

**Comment by deepesh-kn** [comment]
> Validators should not sign based on Core:proposeMetablock; the signatures have already been created during the flow of ProtoCore;

> argument for emitting event is for the tests

In addition to testing, it will also be needed by the validators to know when they can start to register their votes on Core. Validators can subscribe to this event(enitity) and when this event is emitted, the signatures that were created during the flow of `ProtoCore` can be used in register votes.
