### ISSUE TITLE
Consensus should track CoreLifetime of core

### ISSUE THREAD

**Issue by 0xsarvesh** [OpenST/compute#66]
Consensus should track the lifetime of the Core which tells the high-level state of Core. 

The lifetime of a Core can be defined as: 
```
    CoreLifetime:undefined
    CoreLifetime:halted
    CoreLifetime:corrupted
    CoreLifetime:creation
    CoreLifetime:genesis
    CoreLifetime:active
```
Undefined: When core doesn't exist. 
Halted: Core stops functioning. 
Corrupted: Committee rejected the proposal/Pre-commit.
Genesis: When Core is `Opened` and no Pre-commit is done by Core. Once the first Pre-commit is received, the `CoreLifeTime` will change to Activated. 
Active: When Core is functioning correctly, the state can be `Opened` and `Precommitted`.
Creation: When Core is created.

**Comment by benjaminbollen** [comment]
@sarvesh-ost the documented enum has `Active`, not `Activated`; please update to
```
    CoreLifetime:undefined
    CoreLifetime:halted
    CoreLifetime:corrupted
    CoreLifetime:creation
    CoreLifetime:genesis
    CoreLifetime:active
```

**Comment by benjaminbollen** [comment]
the move from `creation` to `genesis` is handled here https://github.com/mosaicdao/mosaic-1/issues/83#issuecomment-562004737

please already set Lifetime to `creation` in `newCore`
