### ISSUE TITLE
Move constants EPOCH_LENGTH from Axiom to Consensus contract. Add a constant MAX_STATE_ROOTS in Consensus contract

### ISSUE THREAD

**Issue by jayeshbairagi** [OpenST/compute#75]
Remove the constant EPOCH_LENGTH from Axiom contract. Add it in Consensus contract. Add a constant MAX_STATE_ROOTS in Consensus contract.

**Comment by deepesh-kn** [comment]
This will be handled in https://github.com/mosaicdao/mosaic-1/issues/100 .
