### ISSUE TITLE
Refactor Axiom::newMetachain

### ISSUE THREAD

**Issue by jayeshbairagi** [OpenST/compute#78]
- Remove all params from axiom:newMetachain()
- Remove all the logic related to maxStateRoot and rootRlpBlockHeader.
- Call consensus.newMetaChain.
- Get the metachainId as the return value of consensus.newMetaChain
- Emit an event MetachainCreated

**Comment by deepesh-kn** [comment]
Due to interdependencies, this will be done in https://github.com/mosaicdao/mosaic-1/issues/100
