### ISSUE TITLE
Introduce core lifetime in Consensus contract

### ISSUE THREAD

**Issue by jayeshbairagi** [OpenST/compute#79]
- Add CoreLifetime mapping in Consensus contract
- Define CoreLifetime enum with the following states
  - CoreLifetime:undefined
  - CoreLifetime:halted
  - CoreLifetime:corrupted
  - CoreLifetime:creation
  - CoreLifetime:genesis
  - CoreLifetime:active

**Comment by benjaminbollen** [comment]
being implemented by @sarvesh-ost in https://github.com/mosaicdao/mosaic-1/issues/66
