### ISSUE TITLE
Refactor Consensus::newMetachain

### ISSUE THREAD

**Issue by jayeshbairagi** [OpenST/compute#80]
- Add a new mapping consensusGateways (metachainId bytes32 -> consensusGateway address)
- Call Axiom::deployMetachainProxies
- Generate metachainId.
- ~~Update the CoreLifetime status to Creation~~ (done in newCore already)
- Update assignments mapping.
- Update consensusGateways mapping
- Return metachainId

**Comment by deepesh-kn** [comment]
Due to interdependencies, this will be done in https://github.com/mosaicdao/mosaic-1/issues/100
