### ISSUE TITLE
Refactor the CoreStatus enum

### ISSUE THREAD

**Issue by jayeshbairagi** [OpenST/compute#81]
- The new statuses are
  - CoreStatus:undefined
  - CoreStatus:terminated
  - CoreStatus:created
  - CoreStatus:opened
  - CoreStatus:precommitted
- Consensus contract should not inherit CoreStatus anymore

**Comment by gulshanvasnani** [comment]
As discussed with the team, changing method name **joinDuringcreation** to **joinBeforeOpen**.
Also, changing **duringCreation** to **beforeOpen**.
