### ISSUE TITLE
Refactor Consensus::newCore

### ISSUE THREAD

**Issue by jayeshbairagi** [OpenST/compute#82]
- Update the function newCore in the consensus contract.
- Remove the uint256 _source param.
- Update CORE_SETUP_CALLPREFIX to exclude _source.
- In Core::setup remove bytes32 _source param.
- Remove committedSource variable from the Core contract.
- Change the CoreStatus to Created

**Comment by abhayks1** [comment]
Handled by PR: https://github.com/mosaicdao/mosaic-1/pull/94
