### ISSUE TITLE
Tracking metablocks' rounds in the Consensus contract.

### ISSUE THREAD

**Issue by pgev** [OpenST/compute#92]
Add in the `Consensus` contract, the following mappings named `metablockchains` and `metablockTips`:
```solidity
  mapping(bytes20 /* chain id */ => mapping(uint256 => MetaBlock)) public metablockchains;
  mapping(bytes20 /* chain id */ => uint256 /* metablock number */) public metablockTips;
```

Metablock's struct:
```solidity
    struct Metablock {
        bytes32 metablockHash;
        uint256 roundBlockNumber;
        MetablockRound round;
    }
```

Metablock's round:
```solidity
  enum MetablockRound {
        Undefined,
        Precommitted,
        CommitteeFormed,
        CommitteeDecided,
        Committed,            
    }
```

The mapping `metablockchains` is updated in the following function calls:
  - `precommitMetablock`
  - `formCommittee`
  - `registerCommitteeDecision`
  - `commitMetablock`

To be able to update `metablockchains` and `metablockTips` mappings one of the below proposals should be picked:

Adding the following two mappings to Consensus:
```solidity
  - mapping(address /* core */ => bytes20 /* chain id */) public cores;
  - mapping(address /* committee */ => bytes20 /* chain id */) public committees;
```

or,

`Consensus` is passing `chainId` into `core` and `committee` on creation. `Core::precommitMetablock`and `Committee::registerCommitteeDecision` specify the `chainId` on calling back. 

Optional (optimization):
  - Keep only latest n number of recent blocks, prune the older data.

**Comment by benjaminbollen** [comment]
Great ticket thx
- mind capitalisation “metablockchains”
- use “metachainId” bytes32 cc @gulshanvasnani on his progress changing this

Thx!

**Comment by pgev** [comment]
@benjaminbollen 

  * Do you mean to have "metablockChains" or "metablockchains"?
  * I would proceed with chainId and depending which PR will be merged first update the second one accordingly.

**Comment by benjaminbollen** [comment]
> Do you mean to have "metablockChains" or "metablockchains"?

I think I would write "metablockchain" as one word, bc I write "blockchain" as one word too. So capitalisation is "metablockchains"

**Comment by pgev** [comment]
https://github.com/mosaicdao/mosaic-1/pull/103
