### ISSUE TITLE
Create internal method `isValidator` in consensus

### ISSUE THREAD

**Issue by jayeshbairagi** [OpenST/compute#95]
- To consistently check if the address is active validator or not
- `function isValidator(address _core, address _validator)`
- Update signature of `enterCommittee` such that it now takes core address and metachainId too,
```
function enterCommittee(
        bytes32 _metachainId,
        address _core,
        address _validator,
        address _furtherMember
    )
```
- this method should be used in `enterCommittee` and `publishEndpoint` (and others)
- requires `core.isValidator(_validator)`; requires `!reputation.isSlashed(_validator)`

**Comment by pgev** [comment]
As it's possible to retrieve `core` from `metachain id`, we should go with the following interface:

```solidity
    function enterCommittee(
          bytes32 _metachainId,
          address _validator,
          address _furtherMember
     )
```

**Comment by jayeshbairagi** [comment]
The `validator` will not necessarily be from the `_core` of the `_metachainId` that is being passed. 
So, we will need both the `_core` and `_metachainId` in the function `enterCommittee` signature.

**Comment by pgev** [comment]
@jayeshbairagi can you please elaborate more. Why do we need to have a `core` of a different metachain on this call (`enterCommittee`)?

**Comment by benjaminbollen** [comment]
@pgev the validators entering the committee are polled over all validators present across all cores.  Therefore the pair `(core, validator)` must be given such that we can check whether it is/was a validator when entering

**Comment by pgev** [comment]
@benjaminbollen thx. Correct. Missed somehow that point.

**Comment by pgev** [comment]
Draft PR https://github.com/pgev/compute/pull/2

**Comment by pgev** [comment]
Fixed in https://github.com/mosaicdao/mosaic-1/pull/103

**Comment by pgev** [comment]
https://github.com/mosaicdao/mosaic-1/pull/103
